# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [7]:
print(np.__version__)

1.23.0


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [9]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [10]:
arr1.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [13]:
arr2 = np.zeros(10)
arr2[4] = 1
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [14]:
arr3 = np.arange(10,49)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [15]:
arr3[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [19]:
arr4 = np.arange(0,9).reshape(3,3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [20]:
arr5 = [1,2,0,0,4,0]
np.nonzero(arr5)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [21]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [23]:
arr6 = np.random.random((3,3,3))
arr6

array([[[0.28149458, 0.66746469, 0.69973333],
        [0.48046441, 0.22316553, 0.3476542 ],
        [0.18660101, 0.50800547, 0.54077151]],

       [[0.95035939, 0.45659028, 0.01216333],
        [0.55426699, 0.68746986, 0.0881287 ],
        [0.54096524, 0.20268841, 0.256056  ]],

       [[0.08658965, 0.2089808 , 0.19221748],
        [0.158312  , 0.63699291, 0.68919577],
        [0.55958254, 0.13085709, 0.65217731]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [29]:
arr7 = np.random.random((10,10))
print(arr7)
print("the maximum value in the array :",np.max(arr7))
print("the maximum value in the array :",np.min(arr7))

[[0.70283335 0.2219451  0.43469632 0.91547456 0.39463928 0.70552113
  0.24726642 0.46182835 0.19300927 0.00380171]
 [0.66128937 0.45157854 0.8071593  0.46985161 0.94895114 0.62054263
  0.30640705 0.55117885 0.00249446 0.27028474]
 [0.99936774 0.80775824 0.84434842 0.33034459 0.82951145 0.52360279
  0.08173321 0.45343561 0.2694791  0.96324881]
 [0.85856611 0.7914387  0.28230611 0.68588141 0.08513403 0.02152596
  0.49006624 0.09001116 0.95520154 0.28227026]
 [0.71386827 0.39272409 0.76508028 0.96561372 0.91813628 0.4940326
  0.35463053 0.23183391 0.57965395 0.7827047 ]
 [0.99655465 0.97044418 0.60996    0.17454959 0.911561   0.38216144
  0.79456134 0.19469993 0.01128332 0.99628422]
 [0.44704197 0.47396091 0.58360363 0.69731482 0.64562173 0.07588312
  0.03216245 0.77675444 0.92224979 0.47467676]
 [0.12365557 0.68473145 0.34796586 0.69181369 0.10200633 0.64303286
  0.43201539 0.85497922 0.49027097 0.89115615]
 [0.82339751 0.62714466 0.75242727 0.40804619 0.46084901 0.84670417
  0.4909897  

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [34]:
arr6 = np.random.random(30)
print(arr6)
print("Mean value of the vector of size 30: ",np.mean(arr6))

[0.06195288 0.40025554 0.12623647 0.89878179 0.75801173 0.89065391
 0.8576294  0.4045551  0.67784229 0.32493397 0.58655393 0.53960749
 0.00868265 0.25009899 0.08775644 0.86396772 0.91961831 0.20954355
 0.50648233 0.01858479 0.29492407 0.54850424 0.60771122 0.3959778
 0.84544333 0.47076711 0.81264765 0.89789711 0.75128081 0.25469169]
Mean value of the vector of size 30:  0.5090531434608924


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [36]:
arr13 = np.zeros((3,3))
print("Original array:")
print("\n")
print(arr13)
print("\n")
print("A 2d array filled with zeros at all borders and all 1’s inside")
print("\n")
arr13[1:-1,1:-1] = 1
print(arr13)

Original array:


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


A 2d array filled with zeros at all borders and all 1’s inside


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [41]:
arr15 = np.ones((3,3))
print("Original array:")
print(arr15)
print("0 on the border and 1 inside in the array")
arr15 = np.pad(arr15, pad_width=1, mode='constant', constant_values=0)
print(arr15)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

nan
False
False
nan
False
nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [44]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [45]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [46]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [47]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [48]:
arr55 = np.random.random((5,5))
arr55 = (arr55 - np.min (arr55)) / (np.max(arr55)-np.min(arr55))
print(arr55)

[[0.54651267 0.40685935 0.10051918 0.90418882 1.        ]
 [0.41627698 0.73819093 0.71997062 0.11311514 0.01096858]
 [0.61438099 0.55334435 0.06082729 0.64403859 0.84746704]
 [0.38743701 0.         0.88066941 0.51434201 0.37971482]
 [0.38529544 0.78742349 0.75917298 0.6574137  0.4818053 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [49]:
color_dtype = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-49-080fb0b43bec>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color_dtype = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [50]:
arr55 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(arr55)

# Alternative solution, in Python 3.5 and above
arr55 = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [51]:
arr66 = np.arange(30)
arr66[(3 < arr66) & (arr66 <= 8)] *= -1
print(arr66)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

### integers to negative power are not allowed

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan
0
array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [52]:
arr66 = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr66)), arr66))

[ -9. -10.   6.  -3.   2.   9.  -3.  -5.  -4.  10.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [56]:
arr56 = np.arange(6,52)
arr57 = np.arange(30,85)
print(np.intersect1d(arr56,arr57))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [168]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

## False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [58]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2022-08-18
2022-08-19
2022-08-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [59]:
arr58 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr58)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [60]:
arr59 = np.ones(3)*1
arr60 = np.ones(3)*2
arr61 = np.ones(3)*3
np.add(arr59,arr60,out=arr60)
np.divide(arr59,2,out=arr59)
np.negative(arr59,out=arr59)
np.multiply(arr59,arr60,out=arr59)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [62]:
arr62 = np.random.uniform(0,30,10)

print (arr62 - arr62%1)
print (np.floor(arr62))
print (np.ceil(arr62)-1)
print (arr62.astype(int))
print (np.trunc(arr62))

[26. 18.  2. 28.  2. 11.  1. 27.  7. 22.]
[26. 18.  2. 28.  2. 11.  1. 27.  7. 22.]
[26. 18.  2. 28.  2. 11.  1. 27.  7. 22.]
[26 18  2 28  2 11  1 27  7 22]
[26. 18.  2. 28.  2. 11.  1. 27.  7. 22.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [64]:
arr63 = np.zeros((5,5))
arr63 += np.arange(5)
print(arr63)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [65]:
def generate():
    for x in range(10):
        yield x
arr67 = np.fromiter(generate(),dtype=float,count=-1)
print(arr67)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [66]:
arr21 = np.linspace(0,10,15,endpoint=False)[1:]
print(arr21)

[0.66666667 1.33333333 2.         2.66666667 3.33333333 4.
 4.66666667 5.33333333 6.         6.66666667 7.33333333 8.
 8.66666667 9.33333333]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [67]:
arr22 = np.random.random(10)
arr22.sort()
arr22

array([0.22239597, 0.33633647, 0.39313022, 0.59041978, 0.59450227,
       0.60154872, 0.61968745, 0.69939341, 0.723951  , 0.99237951])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [69]:
arr23 = np.arange(30)
np.add.reduce(arr23)

435

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [71]:
A = np.random.randint(0,20,5)
B = np.random.randint(0,21,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [73]:
arr24 = np.zeros(10)
arr24.flags.writeable = False
arr24[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [74]:
arr25 = np.random.random((10,2))
Z,L = arr25[:,0], arr25[:,1]
P = np.sqrt(Z**2+L**2)
Q = np.arctan2(Z,L)
print(P)
print(Q)

[0.9294618  1.33683573 1.07765163 1.0097944  0.67295342 0.73045121
 0.76064085 1.12734715 0.43027439 0.93859164]
[0.73186274 0.80997846 0.96382235 0.19432988 0.37103278 1.37465648
 1.31587687 0.94066906 1.27969066 0.22937526]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [75]:
arr26 = np.random.random(10)
arr26[arr26.argmax()] = 0
print(arr26)

[0.         0.33146962 0.42643661 0.58208095 0.96261209 0.56695124
 0.42562333 0.61557213 0.21744231 0.73693407]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [77]:
arr27 = np.zeros((5,5), [('x',float),('y',float)])
arr27['x'], arr27['y'] = np.meshgrid(np.linspace(0,100,5),np.linspace(0,100,5))
print(arr27)

[[(  0.,   0.) ( 25.,   0.) ( 50.,   0.) ( 75.,   0.) (100.,   0.)]
 [(  0.,  25.) ( 25.,  25.) ( 50.,  25.) ( 75.,  25.) (100.,  25.)]
 [(  0.,  50.) ( 25.,  50.) ( 50.,  50.) ( 75.,  50.) (100.,  50.)]
 [(  0.,  75.) ( 25.,  75.) ( 50.,  75.) ( 75.,  75.) (100.,  75.)]
 [(  0., 100.) ( 25., 100.) ( 50., 100.) ( 75., 100.) (100., 100.)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [78]:
X = np.arange(50)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

1.74706789441092e+24


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [79]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [82]:
np.set_printoptions(threshold=float("inf"))
arr28 = np.zeros((10,10))
print(arr28)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [83]:
arr29 = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr29-v)).argmin()
print(arr29[index])

96


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [85]:
arr30 = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-85-5388e9ebc27b>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr30 = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [86]:
import scipy
import scipy.spatial
arr31 = np.random.random((10,2))
X,Y = np.atleast_2d(arr31[:,0], arr31[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

arr31 = np.random.random((10,2))
D = scipy.spatial.distance.cdist(arr31,arr31)
print(D)

[[0.         0.68299953 0.18985892 0.48263808 0.65390473 0.74169698
  0.72974702 0.88069731 0.27765428 0.75497317]
 [0.68299953 0.         0.55827319 0.23333758 0.45779038 0.59837777
  0.3861606  0.57729713 0.46106613 0.09764246]
 [0.18985892 0.55827319 0.         0.40341222 0.46432919 0.77223112
  0.70195708 0.87982357 0.2833267  0.61492007]
 [0.48263808 0.23333758 0.40341222 0.         0.52088987 0.4637676
  0.31885157 0.51466808 0.23259314 0.32686809]
 [0.65390473 0.45779038 0.46432919 0.52088987 0.         0.98393037
  0.81053792 1.0105631  0.61297201 0.43116555]
 [0.74169698 0.59837777 0.77223112 0.4637676  0.98393037 0.
  0.2299075  0.18372193 0.49066626 0.68800401]
 [0.72974702 0.3861606  0.70195708 0.31885157 0.81053792 0.2299075
  0.         0.20038681 0.45244737 0.46890818]
 [0.88069731 0.57729713 0.87982357 0.51466808 1.0105631  0.18372193
  0.20038681 0.         0.61142362 0.6520831 ]
 [0.27765428 0.46106613 0.2833267  0.23259314 0.61297201 0.49066626
  0.45244737 0.6114236

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [87]:
arr32 = np.arange(10, dtype=np.float32)
arr32 = arr32.astype(np.int32, copy=False)
print(arr32)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [88]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
arr33 = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(arr33)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-88-90be987968c5>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr33 = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [90]:
arr34 = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr34):
    print(index, value)
for index in np.ndindex(arr34.shape):
    print(index, arr34[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [91]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [93]:
n = 10
p = 3
arr35 = np.zeros((n,n))
np.put(arr35, np.random.choice(range(n*n), p, replace=False),1)
print(arr35)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [94]:
arr36 = np.random.rand(5, 10)
arr37 = arr36 - arr36.mean(axis=1, keepdims=True)
print(arr37)

[[ 0.46113054 -0.3913121  -0.01960896  0.38765428 -0.15392423 -0.28677922
  -0.43761157  0.45037278 -0.29692729  0.28700577]
 [-0.34483095 -0.1955319  -0.14610612  0.55482593 -0.07036874 -0.15321798
   0.09538182 -0.16747112 -0.18967515  0.61699421]
 [-0.22284664  0.29911023  0.5192714  -0.38062901 -0.07388845 -0.07283387
  -0.07759634  0.08251867 -0.20837747  0.1352715 ]
 [-0.30661028  0.03939217 -0.33252988  0.10204558  0.58951824 -0.12825174
  -0.04893937 -0.29953384  0.11589924  0.26900987]
 [ 0.27232608 -0.30502948 -0.16840509  0.31739844  0.30008512 -0.13286107
   0.33077901  0.0467495  -0.24981252 -0.41122998]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [95]:
arr37 = np.random.randint(0,10,(3,3))
print(arr37)
print(arr37[arr37[:,1].argsort()])

[[0 1 7]
 [1 4 4]
 [2 9 8]]
[[0 1 7]
 [1 4 4]
 [2 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [96]:
arr38 = np.random.randint(0,3,(3,10))
print((~arr38.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [97]:
arr39 = np.random.uniform(0,1,10)
z = 0.5
m = arr39.flat[np.abs(arr39 - z).argmin()]
print(m)

0.6179434916656473


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [99]:
arr40 = np.arange(3).reshape(3,1)
arr41 = np.arange(2,5).reshape(1,3)
it = np.nditer([arr40,arr41,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[2 3 4]
 [3 4 5]
 [4 5 6]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [100]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [103]:
arr42 = np.ones(10)
arr43 = np.random.randint(0,len(Z),20)
np.add.at(arr42, arr43, 1)
print(arr42)

[3. 4. 2. 4. 1. 6. 4. 3. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [102]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[2. 3. 1. 3. 4. 4. 5. 3. 1. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [104]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [105]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 58 50 44]
 [56 69 51 51]
 [50 53 68 67]]
[[63 58 50 44]
 [56 69 51 51]
 [50 53 68 67]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [106]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.52269557 0.56335141 0.37926662 0.5723471  0.56152603 0.25996216
 0.62015675 0.41851971 0.69786603 0.51421837]
0    0.522696
1    0.563351
2    0.379267
3    0.572347
4    0.561526
5    0.259962
6    0.620157
7    0.418520
8    0.697866
9    0.514218
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [107]:
arr42 = np.random.uniform(0,1,(5,5))
arr43 = np.random.uniform(0,1,(5,5))

np.diag(np.dot(arr42, arr43))

array([1.28941669, 1.12741822, 1.1782462 , 1.71590332, 0.6175217 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [108]:
arr44 = np.array([1,2,3,4,5])
nz = 3
arr45 = np.zeros(len(arr44) + (len(arr44)-1)*(nz))
arr45[::nz+1] = arr44
print(arr45)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [109]:
arr46 = np.ones((5,5,3))
arr47 = 2*np.ones((5,5))
print(arr46 * arr47[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [110]:
arr48 = np.arange(25).reshape(5,5)
arr48[[0,1]] = arr48[[1,0]]
print(arr48)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [111]:
faces = np.random.randint(0,100,(10,3))
arr49 = np.roll(faces.repeat(2,axis=1),-1,axis=1)
arr49 = arr49.reshape(len(arr49)*3,2)
arr49 = np.sort(arr49,axis=1)
arr50 = arr49.view( dtype=[('p0',arr49.dtype),('p1',arr49.dtype)] )
arr50 = np.unique(arr50)
print(arr50)

[( 0, 48) ( 0, 65) ( 3, 56) (11, 59) (11, 60) (17, 25) (17, 29) (17, 59)
 (17, 89) (24, 63) (24, 89) (25, 29) (31, 43) (31, 64) (39, 39) (39, 66)
 (42, 57) (43, 64) (48, 65) (49, 76) (49, 80) (56, 56) (57, 57) (59, 60)
 (59, 89) (63, 89) (76, 80)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [113]:
arr51 = np.bincount([1,1,2,3,4,4,6])
arr52 = np.repeat(np.arange(len(arr51)), arr51)
print(arr52)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [114]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr53 = np.arange(20)
print(moving_average(arr53, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [115]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
arr54 = rolling(np.arange(10), 3)
print(arr54)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [116]:
arr55 = np.random.randint(0,2,100)
np.logical_not(arr55, out=arr55)

arr55 = np.random.uniform(-1.0,1.0,100)
np.negative(arr55, out=arr55)


array([ 0.47252218,  0.28559769, -0.38487324, -0.98082282, -0.44245728,
       -0.94961537,  0.53106441,  0.61696667, -0.95146723, -0.23702685,
       -0.23816434, -0.15436491,  0.93359305, -0.2848845 , -0.16933518,
       -0.71039999, -0.03243416,  0.78823861, -0.96860577,  0.11346263,
        0.3686909 ,  0.84481432, -0.66613425, -0.42929455, -0.17950928,
        0.81290689, -0.40498759,  0.72671287,  0.8329018 ,  0.42156916,
       -0.82985446,  0.12639734, -0.84420799,  0.48517749,  0.145012  ,
       -0.71897532,  0.94266694,  0.81116327,  0.8284386 , -0.64908454,
        0.72645385, -0.36032687, -0.49109296,  0.00473057, -0.02234232,
       -0.23334736, -0.02360387, -0.19571496,  0.74686988, -0.79340495,
        0.17736558, -0.08164529, -0.5377563 , -0.78291048, -0.02750366,
       -0.89351887, -0.00306272,  0.42905642,  0.01481956, -0.08232768,
       -0.41913066, -0.36036442,  0.08099926,  0.04212618,  0.76116158,
        0.49964834,  0.8470402 ,  0.97592936, -0.54436536,  0.05

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [119]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-30,30,(10,2))
P1 = np.random.uniform(-30,30,(10,2))
p  = np.random.uniform(-30,30,( 1,2))
print(distance(P0, P1, p))

[47.93968801 26.08471087 21.20935481  7.25858248 33.17348332 36.0884036
  1.28452772 33.43304247 35.27696199  2.6395056 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [120]:
P0 = np.random.uniform(-30,30, (10,2))
P1 = np.random.uniform(-30,30,(10,2))
p = np.random.uniform(-30,30, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[28.42195889  1.7075208   7.43809458 18.95293368 18.16888287 31.6311287
   3.51426483  9.47477651 17.9367562  10.76742373]
 [ 2.4552618  13.51548941 35.58530285 15.77706041 11.71618717  1.68641702
  16.42311796 16.22372887 24.43312104 15.03349352]
 [23.90931521  1.38756145  2.85264368 17.12208612 13.735079   26.93429014
   6.37611626  7.78279781 12.82400542  9.0614065 ]
 [ 6.89198685 28.92276985 16.59139517 14.69473444  4.19094555 12.36589648
  34.94538576 39.02199071 13.22150736 40.26458908]
 [ 5.55920427 30.53599714 16.60464212 16.33337423  5.55359233 11.11725009
  36.57406204 40.18019016 12.57869765 41.41938842]
 [ 1.0749424  31.58531918  3.01549172 13.52712567 11.80568888  3.51858486
  36.85820866 29.3907021   0.71972976 30.60552589]
 [18.34178759  9.88851382  6.35443381  7.50992975  7.90885138 22.06737139
  15.15413899 16.79930116 12.32429356 18.06558661]
 [ 6.41371116 14.4376295  12.87059801  8.37431104  3.53471502  8.93270282
  18.64864842  3.71388484  5.69529178  4.93918678]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [128]:
arr56 = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape, dtype=arr56.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(arr56.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
print(arr56)
print(R)

[[2 8 5 6 2 5 4 5 7 3]
 [5 4 2 7 9 4 4 3 5 3]
 [0 4 7 8 3 2 5 8 0 5]
 [1 1 6 7 5 1 7 2 1 4]
 [5 0 0 7 9 7 6 8 7 6]
 [1 1 1 0 2 7 3 7 9 4]
 [1 9 8 5 6 8 5 9 2 2]
 [5 7 4 7 9 4 2 8 5 7]
 [3 3 3 4 2 3 9 2 3 8]
 [7 9 8 5 8 6 8 5 8 5]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [129]:
arr57 = np.arange(1,15,dtype=np.uint32)
arr58 = stride_tricks.as_strided(arr57,(11,4),(4,4))
print(arr58)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [131]:
arr59 = np.random.uniform(0,10,(30,30))
arr60, arr61, arr62 = np.linalg.svd(arr59)
rank = np.sum(arr61 > 1e-10)
print(rank)

30


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [132]:
arr63 = np.random.randint(0,20,50)
print(np.bincount(arr63).argmax())

17


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [133]:
arr64 = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr64.shape[0]-3)
j = 1 + (arr64.shape[1]-3)
arr65 = stride_tricks.as_strided(arr64, shape=(i, j, n, n), strides=arr64.strides + arr64.strides)
print(arr65)

[[[[4 3 2]
   [3 1 1]
   [1 3 2]]

  [[3 2 2]
   [1 1 1]
   [3 2 3]]

  [[2 2 0]
   [1 1 3]
   [2 3 3]]

  [[2 0 4]
   [1 3 3]
   [3 3 4]]

  [[0 4 3]
   [3 3 4]
   [3 4 4]]

  [[4 3 1]
   [3 4 4]
   [4 4 3]]

  [[3 1 0]
   [4 4 4]
   [4 3 2]]

  [[1 0 4]
   [4 4 1]
   [3 2 4]]]


 [[[3 1 1]
   [1 3 2]
   [4 0 3]]

  [[1 1 1]
   [3 2 3]
   [0 3 0]]

  [[1 1 3]
   [2 3 3]
   [3 0 0]]

  [[1 3 3]
   [3 3 4]
   [0 0 2]]

  [[3 3 4]
   [3 4 4]
   [0 2 2]]

  [[3 4 4]
   [4 4 3]
   [2 2 0]]

  [[4 4 4]
   [4 3 2]
   [2 0 3]]

  [[4 4 1]
   [3 2 4]
   [0 3 2]]]


 [[[1 3 2]
   [4 0 3]
   [0 0 0]]

  [[3 2 3]
   [0 3 0]
   [0 0 4]]

  [[2 3 3]
   [3 0 0]
   [0 4 2]]

  [[3 3 4]
   [0 0 2]
   [4 2 1]]

  [[3 4 4]
   [0 2 2]
   [2 1 2]]

  [[4 4 3]
   [2 2 0]
   [1 2 2]]

  [[4 3 2]
   [2 0 3]
   [2 2 0]]

  [[3 2 4]
   [0 3 2]
   [2 0 0]]]


 [[[4 0 3]
   [0 0 0]
   [3 4 0]]

  [[0 3 0]
   [0 0 4]
   [4 0 4]]

  [[3 0 0]
   [0 4 2]
   [0 4 4]]

  [[0 0 2]
   [4 2 1]
   [4 4 3]]

  [[0 2 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [134]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 13  7  9  7]
 [13  4  5 11  7]
 [ 7  5  5 42 11]
 [ 9 11 42  6  6]
 [ 7  7 11  6  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [135]:
p, n = 10, 20
arr66 = np.ones((p,n,n))
arr67 = np.ones((p,n,1))
arr68 = np.tensordot(arr66, arr67, axes=[[0, 2], [0, 1]])
print(arr68)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [136]:
arr69 = np.ones((16,16))
k = 4
arr70 = np.add.reduceat(np.add.reduceat(arr69, np.arange(0, arr69.shape[0], k), axis=0),np.arange(0, arr69.shape[1], k), axis=1)
print(arr70)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [138]:
def iterate(arr71):
    # Count neighbours
    N = (arr71[0:-2,0:-2] + arr71[0:-2,1:-1] + arr71[0:-2,2:] +
         arr71[1:-1,0:-2]                + arr71[1:-1,2:] +
         arr71[2:  ,0:-2] + arr71[2:  ,1:-1] + arr71[2:  ,2:])

    # Apply rules
    birth = (N==3) & (arr71[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (arr71[1:-1,1:-1]==1)
    arr71[...] = 0
    arr71[1:-1,1:-1][birth | survive] = 1
    return arr71

arr71 = np.random.randint(0,2,(50,50))
for i in range(100): 
    arr71 = iterate(arr71)
print(arr71)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [139]:
arr72 = np.arange(10000)
np.random.shuffle(arr72)
n = 5

print(arr72[np.argsort(arr72)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [140]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [144]:
arr73 = np.array([("RAGHU", 2.5, 3),("VENKATA", 3.6, 2)])
arr74 = np.core.records.fromarrays(arr73.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(arr74)

[(b'RAGHU', 2.5, 3) (b'VENKATA', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [145]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.01 s ± 20.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
576 ms ± 96.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
317 ms ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [146]:
arr75 = np.random.randint(0,5,(8,3))
arr76 = np.random.randint(0,5,(2,2))

arr77 = (arr75[..., np.newaxis, np.newaxis] == arr76)
arr78 = np.where(arr77.any((3,1)).all(1))[0]
print(arr78)

[0 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [149]:
arr79 = np.random.randint(0,5,(10,3))
print(arr79)
# solution for arrays of all dtypes (including string arrays and record arrays)
arr80 = np.all(arr79[:,1:] == arr79[:,:-1], axis=1)
arr81 = arr79[~arr80]
print(arr81)

[[1 4 0]
 [1 3 0]
 [0 3 0]
 [1 3 1]
 [4 4 4]
 [1 1 1]
 [4 0 0]
 [3 1 2]
 [2 0 1]
 [2 2 0]]
[[1 4 0]
 [1 3 0]
 [0 3 0]
 [1 3 1]
 [4 0 0]
 [3 1 2]
 [2 0 1]
 [2 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [150]:
arr82 = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
arr83 = ((arr82.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(arr83[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [151]:
arr84 = np.random.randint(0,2,(6,3))
arr85 = np.ascontiguousarray(arr84).view(np.dtype((np.void, arr84.dtype.itemsize * arr84.shape[1])))
_, idx = np.unique(arr85, return_index=True)
arr86 = arr84[idx]
print(arr86)

[[0 0 1]
 [0 1 0]
 [0 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [160]:
arr87 = np.random.uniform(0,1,10)
arr88= np.random.uniform(0,1,10)

print(np.einsum('i->', arr87))
print(np.einsum('i,i->i', arr87, arr88))
print(np.einsum('i,i', arr87, arr88))
print(np.einsum('i,j->ij', arr87, arr88))

5.807010273098185
[0.39457942 0.25577698 0.05249281 0.11746951 0.32418403 0.30982183
 0.00180231 0.42661812 0.63574062 0.06845666]
2.586942286663403
[[0.39457942 0.36714904 0.05907846 0.25958498 0.22609449 0.61716945
  0.0042526  0.32654688 0.64253111 0.06031238]
 [0.27488654 0.25577698 0.04115743 0.18084171 0.15751032 0.42995546
  0.00296261 0.2274912  0.44762385 0.04201705]
 [0.35059445 0.32622182 0.05249281 0.23064825 0.20089105 0.54837169
  0.00377855 0.29014571 0.57090621 0.05358918]
 [0.17855829 0.16614527 0.02673467 0.11746951 0.10231412 0.27928654
  0.00192442 0.14777165 0.29076341 0.02729305]
 [0.56576499 0.52643413 0.08470925 0.37220414 0.32418403 0.88492418
  0.00609757 0.46821701 0.92128882 0.0864785 ]
 [0.19808064 0.18431046 0.02965765 0.13031282 0.11350045 0.30982183
  0.00213483 0.163928   0.3225535  0.03027709]
 [0.16722843 0.15560304 0.0250383  0.11001585 0.0958221  0.26156529
  0.00180231 0.13839527 0.27231393 0.02556126]
 [0.51549942 0.47966293 0.07718323 0.33913555 

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [164]:
arr89 = np.arange(0, 10*np.pi, 0.1)
n = 1
arr90 = n*arr89*np.cos(arr89)
arr91 = n*arr89*np.sin(arr89)

arr92 = (np.diff(arr90)**2 + np.diff(arr91)**2)**.5 
arr93 = np.zeros_like(arr90)
arr93[1:] = np.cumsum(arr92)                # integrate path
arr93_int = np.linspace(0, arr93.max(), 200) # regular spaced path
arr90_int = np.interp(arr93_int, arr93, arr90)       # integrate path
arr91_int = np.interp(arr93_int, arr93, arr91)

print(arr93_int)
print(arr90_int)
print(arr91_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [165]:
arr94 = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(arr94, 1) == 0, axis=-1)
M &= (arr94.sum(axis=-1) == n)
print(arr94[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [166]:
arr95 = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, arr95.size, (N, X.size))
means = arr95[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.27505949  0.15236321]
